spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    template:
      exchange: exchange1
  application:
    name: rabbitmq
server:
  port: 8081
  servlet:
    context-path: /
